#------------------------------------------------------
#1. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d
#    -- this command will start the containers in detached mode without rebuilding the images (if they exist)
#
#2. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d --build
#    --this command forces to rebuild the images even if they exist
#-------------------------------------------------------



services:


  mongodb:
    image: mongo:latest

    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod -auth
    container_name: mongodb
    networks:
      - spring

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8082:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - spring
networks:
  spring:
    driver: bridge








